# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('ori', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Crime2012',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(blank=True, null=True)),
                ('murder', models.IntegerField(blank=True, null=True)),
                ('rape', models.IntegerField(blank=True, null=True)),
                ('robbery', models.IntegerField(blank=True, null=True)),
                ('assault', models.IntegerField(blank=True, null=True)),
                ('burglary', models.IntegerField(blank=True, null=True)),
                ('larceny', models.IntegerField(blank=True, null=True)),
                ('gta', models.IntegerField(blank=True, null=True)),
                ('ori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucr.Agency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crime2013',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(blank=True, null=True)),
                ('murder', models.IntegerField(blank=True, null=True)),
                ('rape', models.IntegerField(blank=True, null=True)),
                ('robbery', models.IntegerField(blank=True, null=True)),
                ('assault', models.IntegerField(blank=True, null=True)),
                ('burglary', models.IntegerField(blank=True, null=True)),
                ('larceny', models.IntegerField(blank=True, null=True)),
                ('gta', models.IntegerField(blank=True, null=True)),
                ('ori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucr.Agency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crime2014',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(blank=True, null=True)),
                ('murder', models.IntegerField(blank=True, null=True)),
                ('rape', models.IntegerField(blank=True, null=True)),
                ('robbery', models.IntegerField(blank=True, null=True)),
                ('assault', models.IntegerField(blank=True, null=True)),
                ('burglary', models.IntegerField(blank=True, null=True)),
                ('larceny', models.IntegerField(blank=True, null=True)),
                ('gta', models.IntegerField(blank=True, null=True)),
                ('ori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucr.Agency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crime2015',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(blank=True, null=True)),
                ('murder', models.IntegerField(blank=True, null=True)),
                ('rape', models.IntegerField(blank=True, null=True)),
                ('robbery', models.IntegerField(blank=True, null=True)),
                ('assault', models.IntegerField(blank=True, null=True)),
                ('burglary', models.IntegerField(blank=True, null=True)),
                ('larceny', models.IntegerField(blank=True, null=True)),
                ('gta', models.IntegerField(blank=True, null=True)),
                ('ori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucr.Agency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crime2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(blank=True, null=True)),
                ('murder', models.IntegerField(blank=True, null=True)),
                ('rape', models.IntegerField(blank=True, null=True)),
                ('robbery', models.IntegerField(blank=True, null=True)),
                ('assault', models.IntegerField(blank=True, null=True)),
                ('burglary', models.IntegerField(blank=True, null=True)),
                ('larceny', models.IntegerField(blank=True, null=True)),
                ('gta', models.IntegerField(blank=True, null=True)),
                ('ori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucr.Agency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
