# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRates2012',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_group', models.CharField(max_length=1)),
                ('violent_crime', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='violent crime rate')),
                ('murder', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='murder rate')),
                ('rape', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='rape rate')),
                ('robbery', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='robber rate')),
                ('assault', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='asssault rate')),
                ('property_crime', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='property crime rate')),
                ('burglary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='burglary rate')),
                ('larceny', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='larceny rate')),
                ('gta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='gta rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupRates2013',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_group', models.CharField(max_length=1)),
                ('violent_crime', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='violent crime rate')),
                ('murder', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='murder rate')),
                ('rape', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='rape rate')),
                ('robbery', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='robber rate')),
                ('assault', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='asssault rate')),
                ('property_crime', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='property crime rate')),
                ('burglary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='burglary rate')),
                ('larceny', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='larceny rate')),
                ('gta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='gta rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupRates2014',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_group', models.CharField(max_length=1)),
                ('violent_crime', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='violent crime rate')),
                ('murder', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='murder rate')),
                ('rape', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='rape rate')),
                ('robbery', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='robber rate')),
                ('assault', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='asssault rate')),
                ('property_crime', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='property crime rate')),
                ('burglary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='burglary rate')),
                ('larceny', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='larceny rate')),
                ('gta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='gta rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupRates2015',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_group', models.CharField(max_length=1)),
                ('violent_crime', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='violent crime rate')),
                ('murder', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='murder rate')),
                ('rape', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='rape rate')),
                ('robbery', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='robber rate')),
                ('assault', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='asssault rate')),
                ('property_crime', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='property crime rate')),
                ('burglary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='burglary rate')),
                ('larceny', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='larceny rate')),
                ('gta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='gta rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupRates2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_group', models.CharField(max_length=1)),
                ('violent_crime', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='violent crime rate')),
                ('murder', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='murder rate')),
                ('rape', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='rape rate')),
                ('robbery', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='robber rate')),
                ('assault', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='asssault rate')),
                ('property_crime', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='property crime rate')),
                ('burglary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='burglary rate')),
                ('larceny', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='larceny rate')),
                ('gta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='gta rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='crime2012',
            name='r_assault',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='asssault rate'),
        ),
        migrations.AddField(
            model_name='crime2012',
            name='r_burglary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='burglary rate'),
        ),
        migrations.AddField(
            model_name='crime2012',
            name='r_gta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='gta rate'),
        ),
        migrations.AddField(
            model_name='crime2012',
            name='r_larceny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='larceny rate'),
        ),
        migrations.AddField(
            model_name='crime2012',
            name='r_murder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='murder rate'),
        ),
        migrations.AddField(
            model_name='crime2012',
            name='r_property_crime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='property crime rate'),
        ),
        migrations.AddField(
            model_name='crime2012',
            name='r_rape',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='rape rate'),
        ),
        migrations.AddField(
            model_name='crime2012',
            name='r_robbery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='robber rate'),
        ),
        migrations.AddField(
            model_name='crime2012',
            name='r_violent_crime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='violent crime rate'),
        ),
        migrations.AddField(
            model_name='crime2013',
            name='r_assault',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='asssault rate'),
        ),
        migrations.AddField(
            model_name='crime2013',
            name='r_burglary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='burglary rate'),
        ),
        migrations.AddField(
            model_name='crime2013',
            name='r_gta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='gta rate'),
        ),
        migrations.AddField(
            model_name='crime2013',
            name='r_larceny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='larceny rate'),
        ),
        migrations.AddField(
            model_name='crime2013',
            name='r_murder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='murder rate'),
        ),
        migrations.AddField(
            model_name='crime2013',
            name='r_property_crime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='property crime rate'),
        ),
        migrations.AddField(
            model_name='crime2013',
            name='r_rape',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='rape rate'),
        ),
        migrations.AddField(
            model_name='crime2013',
            name='r_robbery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='robber rate'),
        ),
        migrations.AddField(
            model_name='crime2013',
            name='r_violent_crime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='violent crime rate'),
        ),
        migrations.AddField(
            model_name='crime2014',
            name='r_assault',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='asssault rate'),
        ),
        migrations.AddField(
            model_name='crime2014',
            name='r_burglary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='burglary rate'),
        ),
        migrations.AddField(
            model_name='crime2014',
            name='r_gta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='gta rate'),
        ),
        migrations.AddField(
            model_name='crime2014',
            name='r_larceny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='larceny rate'),
        ),
        migrations.AddField(
            model_name='crime2014',
            name='r_murder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='murder rate'),
        ),
        migrations.AddField(
            model_name='crime2014',
            name='r_property_crime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='property crime rate'),
        ),
        migrations.AddField(
            model_name='crime2014',
            name='r_rape',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='rape rate'),
        ),
        migrations.AddField(
            model_name='crime2014',
            name='r_robbery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='robber rate'),
        ),
        migrations.AddField(
            model_name='crime2014',
            name='r_violent_crime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='violent crime rate'),
        ),
        migrations.AddField(
            model_name='crime2015',
            name='r_assault',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='asssault rate'),
        ),
        migrations.AddField(
            model_name='crime2015',
            name='r_burglary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='burglary rate'),
        ),
        migrations.AddField(
            model_name='crime2015',
            name='r_gta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='gta rate'),
        ),
        migrations.AddField(
            model_name='crime2015',
            name='r_larceny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='larceny rate'),
        ),
        migrations.AddField(
            model_name='crime2015',
            name='r_murder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='murder rate'),
        ),
        migrations.AddField(
            model_name='crime2015',
            name='r_property_crime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='property crime rate'),
        ),
        migrations.AddField(
            model_name='crime2015',
            name='r_rape',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='rape rate'),
        ),
        migrations.AddField(
            model_name='crime2015',
            name='r_robbery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='robber rate'),
        ),
        migrations.AddField(
            model_name='crime2015',
            name='r_violent_crime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='violent crime rate'),
        ),
        migrations.AddField(
            model_name='crime2016',
            name='r_assault',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='asssault rate'),
        ),
        migrations.AddField(
            model_name='crime2016',
            name='r_burglary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='burglary rate'),
        ),
        migrations.AddField(
            model_name='crime2016',
            name='r_gta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='gta rate'),
        ),
        migrations.AddField(
            model_name='crime2016',
            name='r_larceny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='larceny rate'),
        ),
        migrations.AddField(
            model_name='crime2016',
            name='r_murder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='murder rate'),
        ),
        migrations.AddField(
            model_name='crime2016',
            name='r_property_crime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='property crime rate'),
        ),
        migrations.AddField(
            model_name='crime2016',
            name='r_rape',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='rape rate'),
        ),
        migrations.AddField(
            model_name='crime2016',
            name='r_robbery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='robber rate'),
        ),
        migrations.AddField(
            model_name='crime2016',
            name='r_violent_crime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='violent crime rate'),
        ),
    ]
