# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucr', '0004_auto_20171006_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_group', models.CharField(max_length=2)),
                ('year', models.PositiveSmallIntegerField()),
                ('cr_homicide', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cr_rape', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cr_robbery', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cr_aggravated_assault', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cr_burglary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cr_larceny', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cr_gta', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentsClearances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('homicide', models.PositiveSmallIntegerField()),
                ('rape', models.PositiveSmallIntegerField()),
                ('robbery', models.PositiveSmallIntegerField()),
                ('aggravated_assault', models.PositiveSmallIntegerField()),
                ('burglary', models.PositiveSmallIntegerField()),
                ('larceny', models.PositiveSmallIntegerField()),
                ('gta', models.PositiveSmallIntegerField()),
                ('clearance_homicide', models.PositiveIntegerField()),
                ('clearance_rape', models.PositiveSmallIntegerField()),
                ('clearance_robbery', models.PositiveSmallIntegerField()),
                ('clearance_aggravated_assault', models.PositiveSmallIntegerField()),
                ('clearance_burglary', models.PositiveSmallIntegerField()),
                ('clearance_larceny', models.PositiveSmallIntegerField()),
                ('clearance_gta', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='assault',
            name='ori',
        ),
        migrations.RemoveField(
            model_name='burglary',
            name='ori',
        ),
        migrations.RemoveField(
            model_name='gta',
            name='ori',
        ),
        migrations.RemoveField(
            model_name='larceny',
            name='ori',
        ),
        migrations.RemoveField(
            model_name='murder',
            name='ori',
        ),
        migrations.DeleteModel(
            name='PopGroupNames',
        ),
        migrations.DeleteModel(
            name='PopGroupRates',
        ),
        migrations.RemoveField(
            model_name='rape',
            name='ori',
        ),
        migrations.RemoveField(
            model_name='robbery',
            name='ori',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='agency_group',
            new_name='pop_group',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='covered_by',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='msa',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='pop10',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='pop11',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='pop12',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='pop13',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='pop14',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='pop15',
        ),
        migrations.AddField(
            model_name='agency',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.DeleteModel(
            name='Assault',
        ),
        migrations.DeleteModel(
            name='Burglary',
        ),
        migrations.DeleteModel(
            name='GTA',
        ),
        migrations.DeleteModel(
            name='Larceny',
        ),
        migrations.DeleteModel(
            name='Murder',
        ),
        migrations.DeleteModel(
            name='Rape',
        ),
        migrations.DeleteModel(
            name='Robbery',
        ),
        migrations.AddField(
            model_name='incidentsclearances',
            name='ori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucr.Agency'),
        ),
    ]
