# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucr', '0006_auto_20171026_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='pop_group',
        ),
        migrations.AlterField(
            model_name='agency',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
