# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucr', '0007_auto_20171106_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentsclearances',
            name='pop_group',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentsclearances',
            name='population',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
