# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucr', '0008_auto_20171106_0342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountyClearances',
        ),
        migrations.AlterField(
            model_name='grouprates',
            name='pop_group',
            field=models.PositiveIntegerField(),
        ),
    ]
