# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucr', '0009_auto_20171106_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
