# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucr', '0010_auto_20171106_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprates',
            name='cr_aggravated_assault',
        ),
        migrations.RemoveField(
            model_name='grouprates',
            name='cr_burglary',
        ),
        migrations.RemoveField(
            model_name='grouprates',
            name='cr_gta',
        ),
        migrations.RemoveField(
            model_name='grouprates',
            name='cr_homicide',
        ),
        migrations.RemoveField(
            model_name='grouprates',
            name='cr_larceny',
        ),
        migrations.RemoveField(
            model_name='grouprates',
            name='cr_rape',
        ),
        migrations.RemoveField(
            model_name='grouprates',
            name='cr_robbery',
        ),
        migrations.AddField(
            model_name='grouprates',
            name='cl_aggravated_assault',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='cl_burglary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='cl_gta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='cl_homicide',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='cl_larceny',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='cl_property',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='cl_rape',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='cl_robbery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='cl_violent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='r_aggravated_assault',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='r_burglary',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='r_gta',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='r_homicide',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='r_larceny',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='r_property',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='r_rape',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='r_robbery',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='grouprates',
            name='r_violent',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
