# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucr', '0011_auto_20171115_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentsclearances',
            name='clearance_property',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentsclearances',
            name='clearance_violent',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentsclearances',
            name='property',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidentsclearances',
            name='violent',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
